apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      app: example-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: example-deployment
    spec:
      containers:
        - name: container
          image: >-
            image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
              protocol: TCP
